[tool.poetry]
name = "sheepy"
version = "0.1.0"
description = ""
authors = ["Jannes <jannes.hachmer@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
poetry-dotenv-plugin = "^0.2.0"
ezsheets = "^2023.8.11"

[tool.poetry.dev-dependencies]
pytest = "^7.4"
ruff = "^0.1.2"
flake8 = "^6.1.0"
black = "^23.10.1"

[tool.black]
line-length = 88

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
