[tool.poetry]
name = "sheepy"
version = "0.1.0"
description = ""
authors = ["Jannes <jannes.hachmer@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
ezsheets = "^2023.8.11"
tabulate = "^0.9.0"

[tool.poetry.dev-dependencies]
pytest = "^7.4"
flake8 = "^6.1.0"
black = "^23.10.1"

[tool.black]
line-length = 88

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
